### PR TITLE
Final touches on mib12 platform: executive reflashing is now done

### PR DESCRIPTION
**Pull request by timburke**
There were a few loose ends on the pic12 8-bit platform that this set of commits resolves. 
- Finished compressing the mib12_executive so that it can be reflashed in place.  Final size on 12lf1822 is 960 words (out of 2048).  This means that we can now order chips with the mib12 executive preflashed on them and never need a pickit 2 again (for 8 bit chips).
- Created mib12_reflasher which takes in as a payload the new executive to reflash and when programmed like a normal application module, takes control and overwrites the mib12 executive with the new version.  This has been tested in hw on pic16lf1847 and works as expected. The overwritten mib12_executive is byte-for-byte correct.
- In order to facilitate the creation of mib12_reflasher, I created hextool.  hextool, like its predecessors mibtool, modtool and pcbtool, is a swiss army knife for one type of task.  In this case, it is manipulating 8 bit hex files.  hextool can compute checksums, patch instructions, verify hex file contents and importantly, insert one hex file into another in a smart way.  This allows building the mib12_executive reflashing hex file which contains a stub (in momo_modules/mib12_reflasher) that just has reflashing code and a payload that contains the actual code to be reflashed over the mib12 executive.
- I also fixed various bugs in the pic12 build system and refactored some of the build tool functionality that was needed for hextool into the pymomo python package.

All of the core 8-bit pic executive code should now be ready to go, including the necessary support tools, build system and unit testing infrastructure.

### CODE REVIEW

**Comment by timburke** [comment]
Example usage:

``` shell
$ mibtool build_reflash mib12_reflash_16lf1847.hex mib12_executive_16lf1847.hex -c 16lf1847 -o refkasher.hex

Analyzing Stub
Chip type:  16lf1847
Defined ranges:
[0x460-0x467]
[0x478-0x4DF]
[0x7F0-0x7FF] <--- MIB Block (skipping)
Skipping mib row: (0x7E0, 0x7FF)
Starting Address for payload: 0x4E0
Maximum payload size: 2816 words

Analyzing Payload
Defined ranges:
[0x0-0x2]
[0x4-0x429]
[0x450-0x462]
[0x8007-0x8008] <--- Config Words (ignored)
Payload Size: 1120
Inserting Hex file [0x0, 0x45F]
Patching start instruction: retlw 0x27
Patching size instruction: retlw 0x23
```

This will intelligently create a mib12_executive reflashing hex file using the information gleaned from the stub and payload hex files as well as the chip type passed in.

**Comment by timburke** [comment]
``` shell
$ mibtool help build_reflash
build_reflash: build an application module for reflashing the mib12_executive

Given a mib12_reflash stub hex file and a new version of the mib12_executive,
combine them into an application module that will reflash the executive onto
the chip type passed.

Usage:
    mibtool build_reflash STUB_FILE PAYLOAD_FILE 

Options:
    -h, --help          show this help message and exit
    -o OUTPUT, --output=OUTPUT
                        output hex file to create
    -c CHIP, --chip=CHIP
                        Chip type that this reflasher corresponds to
```

**Comment by amcgee** [comment]
This was a bit too big of a change to review completely but I trust it works.  One question:

Shouldn't we only be checking in the .mib files, not the command_map.asm files they generate?  The build process should generate that file automatically, and we should be able to de-duplicate the MIB definitions.  Or am I missing something here?

**Comment by timburke** [comment]
Yup you're right.  This commit should (and I believe does) only contain .mib files.  I also git rm'ed the old command_map.asm files that I could find, which is why they show up in the file list.  Some may persist on older modules until they get fixed and brought into the new build system but this commit doesn't affect those.  The only command_map.asm file still around should be the template used to generate them during the build process. It's in config/templates/command_map.asm

As you say, the build system builds a command_map.asm file for each pic12 module during the build process and those are not checked in.

**Comment by amcgee** [comment]
Awesome!

**Pull request merged**
