### PR TITLE
Update gsm_module to be compatible with v5 hardware and bugfix pic12 build system

### PR DESCRIPTION
**Pull request by timburke**
This PR updates the gsm_module to be compatible with the latest v5 gsm board hardware.  If does the following:
- Updates the pic12 build system to look for module_settings.json files to allow for local module settings
- Updates pic12_executive and gsm_module to use module_settings.json
- Makes gsm_module target two architectures to produce a v5 hardware (microsim) and v4 hardware compatible hex file.
- Fixes target name parsing in unit testing for pic12 to enable proper generation of unit testing summaries.
- Updates gsm_module code to be compatible with both v5 and v4 gsm hardware.
- Adds port_definitions.h and updates port.h to encode knowledge of what ports on each chip can be made analog.  This allows application code to make a pin ANALOG when possible without having to know whether the physical pin that it is controlling on each target architecture supports setting the pin to analog.  Often you want to set a pin as analog if possible to save power but not care if it is not supported since it's not required from a functionality standpoint. This was necessary to implement now since some of the pins on v5 were not analog-able whereas they were on v4 gsm hardware.

### CODE REVIEW

**Comment by timburke** [comment]
@amcgee I updated the gsm_module code to be compatible with the latest gsm_module hardware.  I tested the hardware as well as a I could and verified that it worked.  However, I don't have a valid SIM so I couldn't test actually sending a text.  I verified that the module powered up, loaded pic12_executive, loaded gsm_module and that I could power on the GSM module, send it AT commands and get the expected responses.

**Comment by amcgee** [comment]
Great, I'll test it with a SIM and merge.  Awesome work!

**Comment by timburke** [comment]
This should be good to go now.  I've updated the PR to remove the last vestiges of global module settings and fixed a compilation bug in the pic12_executive on 12lf1822 chips.

**Comment by amcgee** [comment]
There were git history issues with this branch.  I've cleared them up and will open a separate pull request.

**Pull request closed without merging**
