### PR TITLE
Fixed momo-commander for compiling on mac os x

### PR DESCRIPTION
**Pull request by timburke**
- Library paths were incorrect on my macbook
- invalid string comparison, need to use strcmp in C/C++
- cleaned up some code
- needed extra include of stdlib on some platforms

### CODE REVIEW

**Comment by timburke** [comment]
This is the version of momo-commander that I use at home.  I couldn't compile the original so I fixed it up on my macbook at home.  Will test on my work macbook pro tomorrow.

**Comment by amcgee** [comment]
It's not common practice to include full versioned dynamic library names in linker commands - usually the installation should symlink binary-compatible versions to the specific versions that are being used.  See http://troydhanson.wordpress.com/2009/05/27/dynamic-library-version-numbers/ for a decent overview.

I'm not sure why your installation doesn't have the symlinks, but changing this will make dev environment setup a bit of a nightmare if the developer has the wrong version installed.

**Comment by timburke** [comment]
I agree.  I’m not sure why it didn’t build for me but this was the only way I could make it do so.  I realize it’s not standard.  You can feel free to reject this one.  I have the python based commander now anyway so this isn’t necessary anymore.

**Comment by amcgee** [comment]
This worked for me as well and I think we're going to move towards deprecating this Commander anyways so I'm going to go ahead and merge this.

**Pull request merged**
