### PR TITLE
Working controller bootloader 

### PR DESCRIPTION
**Pull request by timburke**
The pic24 controller now has a working bootloader that can be controlled from modtool.  Instructions will be posted onto the wiki detailing how it works and how to use it.  For now, I'll just summarize the features:
- bootloader always runs before main firmware so it can't get locked out.
- there is a modtool recover command that will recover a bricked controller if bad firmware is loaded and a new firmware cannot be pushed
- modtool reflash --controller <hexfile> will automatically reflash the controller.

This also adds basic support for scripted hw testing in modtool as well as new controller functionality like bus_reset to reset all of the modules.

Stay tuned for links to the documentation on the wiki.

### CODE REVIEW

**Comment by timburke** [comment]
Instructions for using modtool are now posted here:
https://github.com/WellDone/MoMo-Firmware/wiki/modtool

**Comment by timburke** [comment]
Closes #13 
Closes #23

**Comment by timburke** [comment]
Also Closes #24.  The MIB calls for resetting the module bus have been implemented into the pymomo.commander controller proxy object.

**Comment by amcgee** [comment]
Yet another epic pull request, you're on fire.  I'm going to merge it and we can iterated on the design if need be, but I think it looks good.

**Pull request merged**
