### PR TITLE
Integrate MIB Domain Specific Language into pic12 build process

### LINKED ISSUE #36: Integrate MIB definitions into pic12 build process
- MIB endpoints and application module information can now be specified in a simple domain specific language.  
- mibtool has been updated to automatically generate command_map.asm files from these .mib files
- the pic12 build system has been updated to integrate these build files into the build process

TODO:
- [x]  check for bugs
- [x] validate output for gsm_module and pv_module
- [x] send pull request

### PR DESCRIPTION
**Pull request by timburke**
Closes #36.

Removes the need to manually create command_map.asm files specifying mib endpoints supported by pic12 application modules. Instead the modules are described using a simple DSL, which is parsed and used to generate the command_map.asm file.  The MIB DSL supports file inclusion and variable definition so you can define well_known features and commands by name and refer to them in all mib modules, rather than having to use potentially volatile numerical identifiers.

### CODE REVIEW

**Comment by amcgee** [comment]
Can you give a brief example of the DSL and command line syntax?

**Comment by timburke** [comment]
From [gsm_module.mib](https://github.com/timburke/MoMo-Firmware/blob/feature-mib-dsl/momo_modules/gsm_module/src/mib/gsm_module.mib)

```
#Module Information
ModuleName = "gsm_com";
ModuleType = 0;
ModuleFlags = 0;

#Supported Feature Information
feature 10
0: _gsm_module_on(0, no);
1: _gsm_power_on(0, no);
2: _gsm_sendcommand(0, yes);
3: _gsm_testsim(0, no);
4: _gsm_dumpbuffer(0, no);

#Communication Channel Feature
feature 11
0: _gsm_openstream(0, yes);
1: _gsm_putstream(0, yes);
2: _gsm_closestream(0, no);
```

.mib files contain variable declarations and command definitions. Command definitions must come after a feature declaration and are specified with:
index: symbol(num_ints, has_buffer);
num_ints is 0-3 and specifies the number of int parameters
has_buffer is either yes or no and specifies if a buffer is expected.
index has to start at 0 and increase sequentially since command numbers require this.  It's made explicit so that everyone's clear on what command a specific definition is meant to define.

In order to process a mib file into a command map.asm file use:

``` shell
mibtool gen -o <output_dir> <input_file.mib>
```

The output is named command_map.asm and put into the specified output directory.  This is what the scons build system does internally to build mib12 application modules

In order to dump a hex file's mib block and see what it contains do:

``` shell
mibtool dump <input.hex>
```

You will see a summary on stdout and mibtool will check the hex file's mib block for validity and display any errors it finds.

[mibtool](https://github.com/timburke/MoMo-Firmware/blob/feature-mib-dsl/tools/bin/mibtool) lives in tools/bin

**Comment by timburke** [comment]
I'm starting to work on language documentation.  It's parsed using the pyparsing module with the grammer in tools/pymomo/mib/descriptor.py.

Feedback is welcome.  Main goal was so that people didn't have to write asm files for pic12 to encode all of the mib information in the right format for the mib12 executive to find.  I kept screwing it up subtly and decided that if the guy who designed it couldn't consistently get it right, it probably wasn't user friendly.  The mib files are one way to remove that need.  

They are used to fill in a command_map.asm template using the Cheetah templating engine.  The template is stored with the other templates in config/templates

**Comment by amcgee** [comment]
Awesome, I think this is a great idea!

**Comment by timburke** [comment]
I should also note that in the code sample where it says:

```
feature: 10
```

It also supports variable definition and usage, so you can also do:

```
include(mib_definitions.mib);

feature: communications
```

where communications is a variable defined either in this file or in the file mib_definitions.mib.

**Comment by amcgee** [comment]
I think we should reconsider having well-known addresses for specific commands.  If commands (and maybe even features) are given bigger GUID ids then different modules can implement them at any "command address" without fear of overloading the address space or preserving backwards-compatibility at low well-known addresses.  This would work if the GUID-address mapping is inspect-able over MIB or reported with the initial module registration.

That being said, this could be overly-complicating at this point, and regardless having this framework is great.  Closing.

**Pull request merged**
